package main

import (
	"text/template"
)

var templates = template.Must(template.New("file").Parse(`
{{define "file"}}// Code generated by deltagen. DO NOT EDIT.
package {{.PackageName}}

type {{.Name}}Delta struct {
	{{range .Fields}}{{.Name}} *{{.Type}}
	{{end}}
}

func (e *{{.Name}}) Clone() *{{.Name}} {
	cp := *e
	return &cp
}

func (e *{{.Name}}) Delta(other *{{.Name}}) *{{.Name}}Delta {
	if other == nil {
		return nil
	}
	d := &{{.Name}}Delta{}
	{{range .Fields}}
	if e.{{.Name}} != other.{{.Name}} {
		v := e.{{.Name}}
		d.{{.Name}} = &v
	}
	{{end}}
	return d
}

func (d *{{.Name}}Delta) ApplyTo(e *{{.Name}}) *{{.Name}} {
	cp := *e
	{{range .Fields}}
	if d.{{.Name}} != nil {
		cp.{{.Name}} = *d.{{.Name}}
	}
	{{end}}
	return &cp
}
{{end}}
`))
